directories = [
  "~/dev",
  "~/dev/sykes",
  "~/dev/msp",
  "~/dev/cdk",
  "~/dev/native",
  "~/dev/guide",
  "~/dev/report",
  "~/personal",
  "~/dotfiles",
  "~/dotfiles/.config",
  "~/github",
  "~/plugins",
  "~/learning",
  "~"
]
display_tilde = true
exclude_current_session = true
navigate_session = true
