set -g mouse on

unbind-key C-b
set -g prefix C-s
bind-key C-s send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g repeat-time 0
set -g history-limit 5000
set-option -g focus-events on
set-option -g detach-on-destroy off

bind c neww -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

bind-key x kill-pane
bind-key X kill-session

bind C-p previous-window
bind C-n next-window

bind C-s switch-client -l

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g status-style "fg=color8"
set -g window-status-current-style "fg=blue bold"
set -g status-left-length 100
set -g status-right-length 100

bind P paste-buffer
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
bind-key -T prefix l send-keys C-u \; send-keys C-l \; run-shell "sleep 0" \; clear-history

source-file ./plugins/vim-tmux-navigator/vim-tmux-navigator.tmux
